### PR TITLE
fix: install experimental debian packages in install-mender.sh

### PR DESCRIPTION
**Pull request by snusifer**
Changelog: Title
Ticket: MEN-5928
Signed-off-by: Mikael Torp-Holte <mikael.torp-holte@northern.tech>

### CODE REVIEW

**Comment by lluiscampos** [comment]
I am not sure this will work as-is. I need more time to look into this.

Meanwhile, the test failure you are getting is not related to this PR but the fact that we have [removed the `artifact_info` file from the package](https://github.com/mendersoftware/mender/pull/1049/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L102). We can remove this check from the test (separate commit :pray: )

**Comment by lluiscampos** [comment]
> Meanwhile, the test failure you are getting is not related to this PR but the fact that we have [removed the `artifact_info` file from the package](https://github.com/mendersoftware/mender/pull/1049/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L102). We can remove this check from the test (separate commit pray )

Sorry, forget this. Already done in #290

**Comment by oleorhagen** [comment]
@snusifer you can now rebase this on top of master, and your pipeliens should be happy

**Comment by snusifer** [comment]
Using a debian buster docker image, i ran:
`./script -c experimental --demo --commercial --jwt-token $JWT_TOKEN mender-gateway mender-monitor mender-monitor-demo`
Then `dpkg -l | grep mender`.

Before PR with experimental:
```
ii  mender-client             3.4.0-1+debian+buster       amd64        Mender client
ii  mender-configure          1.0.4-1+debian+buster       all          Mender Configure
ii  mender-configure-demo     1.0.4-1+debian+buster       all          Mender Configure Demo
ii  mender-configure-timezone 1.0.4-1+debian+buster       all          Mender Configure Timezone
ii  mender-connect            2.1.0-1+debian+buster       amd64        Mender Connect
ii  mender-gateway            1.0.1-1+debian+buster       amd64        Mender Gateway
ii  mender-monitor            1.2.1-1+debian+buster       all          Mender Monitor client
ii  mender-monitor-demo       1.2.1-1+debian+buster       all          Adds demo functionality to Mender Monitor.
```
My PR with stable:
```
ii  mender-client             3.4.0-1+debian+buster       amd64        Mender client
ii  mender-configure          1.0.4-1+debian+buster       all          Mender Configure
ii  mender-configure-demo     1.0.4-1+debian+buster       all          Mender Configure Demo
ii  mender-configure-timezone 1.0.4-1+debian+buster       all          Mender Configure Timezone
ii  mender-connect            2.1.0-1+debian+buster       amd64        Mender Connect
ii  mender-gateway            1.0.1-1+debian+buster       amd64        Mender Gateway
ii  mender-monitor            1.2.1-1+debian+buster       all          Mender Monitor client
ii  mender-monitor-demo       1.2.1-1+debian+buster       all          Adds demo functionality to Mender Monitor.
```
My PR with experimental:
```
ii  mender-client             3.4.0-1+debian+buster                                      amd64        Mender client
ii  mender-configure          1.0.4-1+debian+buster                                      all          Mender Configure
ii  mender-configure-demo     1.0.4-1+debian+buster                                      all          Mender Configure Demo
ii  mender-configure-timezone 1.0.4-1+debian+buster                                      all          Mender Configure Timezone
ii  mender-connect            2.1.0-1+debian+buster                                      amd64        Mender Connect
ii  mender-gateway            1.1.0~git20220924.aff1301-1+debian+buster+builder658685862 amd64        Mender Gateway
ii  mender-monitor            1.3.0~git20220924.6c31bf6-1+debian+buster+builder658685862 all          Mender Monitor client
ii  mender-monitor-demo       1.3.0~git20220924.6c31bf6-1+debian+buster+builder658685862 all          Adds demo functionality to Mender Monitor.
```

Missing anything here?

**Comment by oleorhagen** [comment]
Well at least it works it looks like. I will leave @lluiscampos have a view also.

**Review by lluiscampos — APPROVED** [review]
Nice work

**Pull request merged**
