### PR TITLE
feat: Add Ubuntu 22 packages

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: Title
Ticket: QA-435

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
That was way easier than anticipated :trophy: 

You need to update [this file](https://github.com/mendersoftware/sre-tools/blob/master/terragrunt/nt-management/us-east-1/provisioner-ansible/roles/mender-repos-apt/files/conf/distributions) (and follow up in Slack for SRE team to actually update it on the VM) before merging this PR.

**Comment by lluiscampos** [comment]
@oleorhagen You also need to update `mender-docs` :+1:

**Comment by oleorhagen** [comment]
Follow-up PRs:
* https://github.com/mendersoftware/sre-tools/pull/213
* https://github.com/mendersoftware/mender-docs/

**Comment by lluiscampos** [comment]
> Follow-up PRs:
> 
>     * [Add Ubuntu Jammy Apt repo support sre-tools#213](https://github.com/mendersoftware/sre-tools/pull/213)

:+1: 

>     * https://github.com/mendersoftware/mender-docs/

:question:

**Review by lluiscampos — CHANGES_REQUESTED** [review]
We also need to update the [install.sh script](https://github.com/mendersoftware/mender-dist-packages/blob/0f84ce6193240534c439b8028c5201b273b38244/scripts/install-mender.sh#L409).

Sorry that I didn't catch this before :sweat_smile:

**Comment by oleorhagen** [comment]
> We also need to update the [install.sh script](https://github.com/mendersoftware/mender-dist-packages/blob/0f84ce6193240534c439b8028c5201b273b38244/scripts/install-mender.sh#L409).
> 
> Sorry that I didn't catch this before sweat_smile

I'm confused, is this not enough?

https://github.com/mendersoftware/mender-dist-packages/pull/266/files#diff-4f0df1d73eedfab863e987b0c7f29079133c80b39e5e68b15eee877095dc612fR410

**Comment by lluiscampos** [comment]
> I'm confused, is this not enough?
> 
> https://github.com/mendersoftware/mender-dist-packages/pull/266/files#diff-4f0df1d73eedfab863e987b0c7f29079133c80b39e5e68b15eee877095dc612fR410

Oh my... :see_no_evil:

**Review by lluiscampos — APPROVED** [review]

**Pull request merged**
