### PR TITLE
ci: Skip building source packages

### PR DESCRIPTION
**Pull request by lluiscampos**
This will also have to be re-enabled with MEN-6579.

### CODE REVIEW

**Comment by lluiscampos** [comment]
@kacf This should workaround the problem that we saw earlier when building the first alpha

**Comment by lluiscampos** [comment]
Pipeline building the alpha tag @ [Pipeline 915096276](https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/pipelines/915096276)

**Review by kacf — APPROVED** [review]
Should we create a ticket to fix this properly?

**Comment by lluiscampos** [comment]
> Should we create a ticket to fix this properly?

I extended the scope of MEN-6579 to cover also this workaround :+1:

**Pull request merged**
