### PR TITLE
pipeline: Publish and reuse Docker images

### PR DESCRIPTION
**Pull request by lluiscampos**
To always build the Docker images from scratch is just a waste... This
commit reworks the pipeline so that the images are only built on changes
to the relevant files; and the packages are build either pulling the
images from upstream or loading the local images.

The docker-build-package script has been reworked to take the package to
build as an input, with the intention in the future to select via
pipeline variables which packages to build.

### CODE REVIEW

**Comment by lluiscampos** [comment]
This PR is born out of frustration... I had to retry [the Docker images build](https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/jobs/1622653674) five times (so far) during the Mender 3.1.0-build6 due to errors in upstream sources.

What do you guys think? Does it make sense?

**Comment by lluiscampos** [comment]
(I have syntax errors in the GitLab pipeline file, but I won't fix it until I get some initial feedback on the approach).

**Review by oleorhagen — APPROVED** [review]

**Review by kacf — APPROVED** [review]
I think it makes sense. I couldn't spot anything wrong, but Gitlab will be the ultimate judge.

**Comment by lluiscampos** [comment]
Thanks for the positive feedback I force-pushed the pipeline fixes (and rebased on top of latest mater)

**Comment by lluiscampos** [comment]
The new commit makes use of https://github.com/mendersoftware/mendertesting/pull/158 to save/load the huge images. I'll merge after green build :crossed_fingers:

**Pull request merged**
