### PR TITLE
MEN-7010: Support for overriding the Debian suffix in the package version

### PR DESCRIPTION
**Pull request by lluiscampos**
So that we can publish new packages of already released software.

### CODE REVIEW

**Comment by lluiscampos** [comment]
Test pipeline for the packages that we will re-publish [here](https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/pipelines/1164838242) with the following CI env variables:
* `MENDER_CONFIGURE_VERSION=1.1.2`
* `MENDER_APP_UPDATE_MODULE_VERSION=1.0.0`
* `MENDER_MONITOR_VERSION=1.3.0`
* `OVERRIDE_DEBIAN_SUFFIX=2`

**Comment by lluiscampos** [comment]
> Test pipeline for the packages that we will re-publish [here](https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/pipelines/1164838242) with the following CI env variables:
> 
>     * `MENDER_CONFIGURE_VERSION=1.1.2`
> 
>     * `MENDER_APP_UPDATE_MODULE_VERSION=1.0.0`
> 
>     * `MENDER_MONITOR_VERSION=1.3.0`
> 
>     * `OVERRIDE_DEBIAN_SUFFIX=2`

New build with the same parameters [here](https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/pipelines/1164977305).

**Comment by lluiscampos** [comment]
> New build with the same parameters [here](https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/pipelines/1164977305).

New [build](https://gitlab.com/Northern.tech/Mender/mender-dist-packages/-/pipelines/1165826388).

**Review by kacf — APPROVED** [review]
👍

**Pull request merged**
